name: DeployEC2

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Instalar dependencias
      run: |
        pip install -r requirements.txt

    - name: Ejecutar pruebas
      run: |
        echo "No hay pruebas aún. Puedes agregar pytest aquí."

    - name: Construir imagen Docker local
      run: docker build -t fastapi-app .

    - name: Desplegar en EC2 vía SSH
      uses: appleboy/ssh-action@v0.1.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # Instalar git si no existe
          if ! command -v git &> /dev/null; then
            sudo yum install -y git
          fi

          # Instalar Docker si no está
          if ! command -v docker &> /dev/null; then
            sudo yum update -y
            sudo yum install -y docker
            sudo service docker start
            sudo usermod -aG docker ec2-user
          fi

          # Instalar Docker Compose si no está
          if ! command -v docker-compose &> /dev/null; then
            sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
          fi
        
          # Ir a home
          cd ~

          # Clonar si no existe
          if [ ! -d "pruebas1507" ]; then
            git clone https://github.com/davmorenoga/pruebas1507.git
          fi

          cd pruebas1507
          git pull origin main

          # Verificar docker-compose.yml
          if [ ! -f "docker-compose.yml" ]; then
            echo "❌ docker-compose.yml no encontrado en $(pwd)"
            exit 1
          fi

          # Ejecutar el stack
          docker-compose down
          docker-compose up -d --build
