name: Login and Push Nexus

on:
  push:
    branches: [main]

jobs:
  Login-and-push-nexus:
    runs-on: ubuntu-latest

    steps:
    - name: Configure Docker for insecure registry
      run: |
        # Crea el archivo de configuraci칩n de Docker para permitir la conexi칩n HTTP a tu Nexus
        echo '{"insecure-registries": ["${{ secrets.NEXUS_DOCKER_REPO_URL }}"]}' | sudo tee /etc/docker/daemon.json
        # Verifica si Docker est치 en ejecuci칩n, si no, intenta iniciarlo
        if ! systemctl is-active --quiet docker; then
          sudo systemctl start docker
        fi

    - name: Log in to Nexus
      uses: docker/login-action@v3
      with:
          registry: ${{ secrets.NEXUS_DOCKER_REPO_URL }}
          username: ${{ secrets.NEXUS_USERNAME }}
          password: ${{ secrets.NEXUS_PASSWORD }}

    - name: Push imagen a Nexus
      run: |
        docker tag fastapi-app ${{ secrets.EC2_HOST }}:8082/fastapi-docker/fastapi-app:latest
        docker push ${{ secrets.EC2_HOST }}:8082/fastapi-docker/fastapi-app:latest
