name: Login and Push to Nexus

on:
  workflow_run:
    workflows: ["CI/CD + Deploy en EC2 (Amazon Linux)"]
    types:
      - completed

jobs:
  login-and-push-nexus:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Verificar secreto NEXUS_DOCKER_REPO_URL
        run: |
          if [ -z "${{ secrets.NEXUS_DOCKER_REPO_URL }}" ]; then
            echo "❌ El secreto NEXUS_DOCKER_REPO_URL está vacío o no existe."
            exit 1
          fi

      - name: Esperar a que Nexus termine de iniciar (60 segundos)
        run: sleep 60

      - name: Configurar Docker para usar Nexus por HTTP
        run: |
          echo "{ \"insecure-registries\": [\"${NEXUS_DOCKER_REPO_URL}\"] }" | sudo tee /etc/docker/daemon.json
          sudo systemctl restart docker
        env:
          NEXUS_URL: ${{ secrets.NEXUS_DOCKER_REPO_URL }}

      - name: Eliminar credenciales previas (opcional)
        run: rm -f ~/.docker/config.json

      - name: Login a Nexus
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.NEXUS_DOCKER_REPO_URL }}
          username: ${{ secrets.NEXUS_USERNAME }}
          password: ${{ secrets.NEXUS_PASSWORD }}

      - name: Construir y subir imagen a Nexus
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.NEXUS_DOCKER_REPO_URL }}/fastapi-docker/fastapi-app:latest
