name: Login and Push Nexus

on:
  push:
    branches: [main]

jobs:
  Login-and-push-nexus:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Configurar Docker para usar Nexus HTTP
      run: |
        echo '{ "insecure-registries": ["${{ secrets.NEXUS_DOCKER_REPO_URL }}"] }' | sudo tee /etc/docker/daemon.json
        sudo systemctl restart docker

    - name: Eliminar credenciales previas (opcional)
      run: rm -f ~/.docker/config.json

    - name: Login a Nexus
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.NEXUS_DOCKER_REPO_URL }}
        username: ${{ secrets.NEXUS_USERNAME }}
        password: ${{ secrets.NEXUS_PASSWORD }}

    - name: Build y push a Nexus (sin usar Docker Hub)
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.NEXUS_DOCKER_REPO_URL }}/fastapi-docker/fastapi-app:latest
